### ISSUE TITLE
New frontpage gets stuck at bottom without pagination and footer

### ISSUE THREAD

**Issue by Monniasza** [PixelcatProductions/CrispCMS-ToS-DR#42]
I can't browse services further, because page ends with service list. Additionally, footer isn't located at bottom of the page.

**Comment by JustinBack** [comment]
Are you by any chance on a mobile device?

Footers are currently disabled on mobiles due to a bug.

As for the frontpage, we display top 10 services and provide a search function to request additional. On the top right there is a menu bar which allows you to open the navigation

**Comment by Monniasza** [comment]
> Are you by any chance on a mobile device?
> 
> Footers are currently disabled on mobiles due to a bug.
> 
> As for the frontpage, we display top 10 services and provide a search function to request additional. On the top right there is a menu bar which allows you to open the navigation

I work on a computer.

**Comment by JustinBack** [comment]
Alright,
do you have a chance to post a screenshot here? The desktop page works fine here on Firefox
![grafik](https://user-images.githubusercontent.com/40178814/102333294-82a93d00-3f8d-11eb-90f1-f4ef7814b8e0.png)

**Comment by Monniasza** [comment]
I use Chrome.
![TOS;DR bug](https://user-images.githubusercontent.com/37037712/102333636-fb0ffe00-3f8d-11eb-8f84-d5a4d7026aba.PNG)
The footer is located in the middle of page

**Comment by JustinBack** [comment]
I can reproduce this on chrome as well, going to push a fix soon!

**Comment by JustinBack** [comment]
Feel free to repon if this issue still occurs for you!

**Comment by Monniasza** [comment]
It works correctly.
