### ISSUE TITLE
Use SVGs for logos instead of "crisp pngs"

### ISSUE THREAD

**Issue by mr-winson** [PixelcatProductions/CrispCMS-ToS-DR#47]
They would look better, scale better, and load faster.

The logos on the new crisp site are better than the original but still a little pixelated 

http://logosvg.com/

**Comment by JustinBack** [comment]
This is what we are doing right now :-)

https://github.com/PixelcatProductions/CrispCMS-ToS-DR/blob/31bef445087f78903346f0f1e841853d70bc938a/pixelcatproductions/class/crisp/api/Phoenix.php#L431

If no SVGs are found, fallback to PNGs.

Good site you have pointed out there, this should help a lot moving over to SVG!

Logos are stored here by the way:

https://github.com/PixelcatProductions/CrispCMS-ToS-DR/tree/master/themes/crisp/img/logo

**Comment by mr-winson** [comment]
Awesome! Don't know PHP but that is good!
