### ISSUE TITLE
Link / logo looks too close

### ISSUE THREAD

**Issue by icecream17** [PixelcatProductions/CrispCMS-ToS-DR#48]
It's just ...stuffed in there uncomfortably
![image](https://user-images.githubusercontent.com/58114641/103252813-0840cb80-4944-11eb-8aba-6d189044ea14.png)

**Comment by JustinBack** [comment]
I see, I'll fix this with a margin so the text moves a bit to the right

**Comment by JustinBack** [comment]
![](https://justinback.jbcdn.net/captures/firefox_0C0OWIOaMk.png) is this better to your liking?

**Comment by icecream17** [comment]
The logo looks better, yeah!

Although now the text isn't really centered, maybe there should be a margin at the right too?

**Comment by JustinBack** [comment]
The logo is centered

![](https://justinback.jbcdn.net/captures/ShareX_bCdux7fkBv.png)

However I don't think I can change the small difference in text height open for suggestions though

![](https://justinback.jbcdn.net/captures/ShareX_Hnqu4DQxso.png)

**Comment by icecream17** [comment]
Oh, I meant the link text,

It looks a bit uncentered, like this:
<pre><code>Logo  Text Grade</code></pre>

Maybe add a right margin to the text:  
<pre><code>Logo  Text  Grade</code></pre>

Or add a ```|```: 
<pre><code>Logo | Text Grade</code></pre>

I tried putting a space instead of ```|``` but it doesn't look right to me....
<pre><code>Logo   Text Grade</code></pre>

**Comment by JustinBack** [comment]
Added `ml-1` to the grade badge

![](https://justinback.jbcdn.net/captures/firefox_NxCy5b5u7s.png)
